logging.level.org.apache.kafka: WARN

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: latest
      group-id: kafka-latency-meter
      enable-auto-commit: true
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

kafka:
  topic: in
  messageSize: 1024
  numMessages: 10000
  ratePerSecond: 500
